/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Specification = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const NutritionData = IDL.Record({
  'fat' : IDL.Float64,
  'fiber' : IDL.Float64,
  'carbohydrates' : IDL.Float64,
  'calories' : IDL.Float64,
  'minerals' : IDL.Text,
  'vitamins' : IDL.Text,
  'protein' : IDL.Float64,
});
export const ProductVariant = IDL.Record({
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const ContactFormEntry = IDL.Record({
  'userType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ProductDetail = IDL.Record({
  'specifications' : IDL.Vec(Specification),
  'description' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'nutritionData' : NutritionData,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProductDetail' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Specification),
        IDL.Nat,
        NutritionData,
        IDL.Text,
        IDL.Vec(ProductVariant),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactFormEntry)], ['query']),
  'getAllProductDetails' : IDL.Func([], [IDL.Vec(ProductDetail)], ['query']),
  'getFormEntry' : IDL.Func([IDL.Nat], [ContactFormEntry], ['query']),
  'getProductDetail' : IDL.Func([IDL.Nat], [IDL.Opt(ProductDetail)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductDetail)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Specification = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const NutritionData = IDL.Record({
    'fat' : IDL.Float64,
    'fiber' : IDL.Float64,
    'carbohydrates' : IDL.Float64,
    'calories' : IDL.Float64,
    'minerals' : IDL.Text,
    'vitamins' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const ProductVariant = IDL.Record({
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const ContactFormEntry = IDL.Record({
    'userType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ProductDetail = IDL.Record({
    'specifications' : IDL.Vec(Specification),
    'description' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'nutritionData' : NutritionData,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProductDetail' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Specification),
          IDL.Nat,
          NutritionData,
          IDL.Text,
          IDL.Vec(ProductVariant),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactFormEntry)], ['query']),
    'getAllProductDetails' : IDL.Func([], [IDL.Vec(ProductDetail)], ['query']),
    'getFormEntry' : IDL.Func([IDL.Nat], [ContactFormEntry], ['query']),
    'getProductDetail' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProductDetail)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductDetail)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };