/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormEntry {
  'userType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'phoneNumber' : string,
}
export interface NutritionData {
  'fat' : number,
  'fiber' : number,
  'carbohydrates' : number,
  'calories' : number,
  'minerals' : string,
  'vitamins' : string,
  'protein' : number,
}
export interface ProductDetail {
  'specifications' : Array<Specification>,
  'description' : string,
  'productId' : bigint,
  'productName' : string,
  'variants' : Array<ProductVariant>,
  'nutritionData' : NutritionData,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface ProductVariant { 'name' : string, 'imageUrl' : string }
export interface Specification { 'key' : string, 'value' : string }
export interface _SERVICE {
  'addProductDetail' : ActorMethod<
    [
      string,
      string,
      string,
      Array<Specification>,
      bigint,
      NutritionData,
      string,
      Array<ProductVariant>,
    ],
    bigint
  >,
  'getAllContactForms' : ActorMethod<[], Array<ContactFormEntry>>,
  'getAllProductDetails' : ActorMethod<[], Array<ProductDetail>>,
  'getFormEntry' : ActorMethod<[bigint], ContactFormEntry>,
  'getProductDetail' : ActorMethod<[bigint], [] | [ProductDetail]>,
  'getProductsByCategory' : ActorMethod<[string], Array<ProductDetail>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];